name       : kactivities-stats
version    : 5.38.0
release    : 4
source     :
    - https://download.kde.org/stable/frameworks/5.38/kactivities-stats-5.38.0.tar.xz : a23955ce584ea0a1be8fe17b0b9cad819279b7518d3a9cf175a40e4bc08fa768
license    :
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
summary    : Library to access statistics collected by the KDE activity manager
description: |
    The KActivitiesStats library provides a querying mechanism for the data that the activitiy manager collects - which documents hae been opened by which applications, and what documents have been linked to which activity. The activity manager also keeps the score for each document which gets higher when a particular document has been often accessed or kept open for longer periods of time. This score is also available through the querying mechanism.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - libboost-devel
setup      : |
    mkdir build && pushd build
    %cmake -DBUILD_QCH=ON ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
