name       : kactivities-stats
version    : 5.39.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.39/kactivities-stats-5.39.0.tar.xz : 9ee15060e4fc2cc6ca9d02a1a196b92c9cdedf437b4d1a56cd6838fe1e76f0a1
license    :
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
summary    : Library to access statistics collected by the KDE activity manager
description: |
    The KActivitiesStats library provides a querying mechanism for the data that the activitiy manager collects - which documents hae been opened by which applications, and what documents have been linked to which activity. The activity manager also keeps the score for each document which gets higher when a particular document has been often accessed or kept open for longer periods of time. This score is also available through the querying mechanism.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - libboost-devel
setup      : |
    mkdir build && pushd build
    %cmake -DBUILD_QCH=ON ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
